name: buildx

on:
  push:
    tags:
      - '*'

env:
  IMAGE_NAME: copa-tokens-server
  DOCKER_USER: orionbcdb
  DOCKER_PLATFORMS: linux/amd64,linux/arm64,linux/arm/v7
  DOCKERFILE: images/Dockerfile

jobs:
  buildx:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Get the latest tag
        id: tag_name
        run: echo ::set-output name=TAG_NAME::${GITHUB_REF#refs/tags/}

      - name: Checkout repository
        uses: actions/checkout@v2

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PWD }}

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Run Buildx
        run: |
          docker buildx build \
            --platform ${{ env.DOCKER_PLATFORMS }} \
            --output "type=image,push=true" \
            --tag ${{ env.DOCKER_USER }}/${{ env.IMAGE_NAME }}:${{ steps.tag_name.outputs.TAG_NAME }} \
            --tag ${{ env.DOCKER_USER }}/${{ env.IMAGE_NAME }}:latest \
            --file ${{ env.DOCKERFILE }} .
